//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccess.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class DetallePedido
    {
        public long NuPedido { get; set; }
        public string producto { get; set; }
        public Nullable<short> cantidad { get; set; }
        public Nullable<double> precioUnitario { get; set; }
    
        public virtual Pedido Pedido { get; set; }
    }
}
